
inputs:
  version:
    description: "A version to install tfstate-lookup"
    default: "v0.3.0"
runs:
  using: "composite"
  steps:
    - run: |
        set -e
        OWNER="fujiwara"
        REPO="tfstate-lookup"
        VERSION="${{ inputs.version }}"
        if [ "${VERSION}" = "latest" ]; then
          DOWNLOAD_URL=$(curl -sS https://api.github.com/repos/${OWNER}/${REPO}/releases/latest|jq -r '.assets[].browser_download_url|select(test("linux_amd64.tar.gz$"))')
        else
          DOWNLOAD_URL=https://github.com/${OWNER}/${REPO}/releases/download/${VERSION}/${REPO}_${VERSION//v/}_linux_amd64.tar.gz
        fi
        cd /tmp
        curl -sfLO ${DOWNLOAD_URL}
        FILENAME=$(basename $DOWNLOAD_URL .tar.gz)
        tar -zxf ${FILENAME}.tar.gz
        sudo install ${REPO} /usr/local/bin/${REPO}
        rm -f ${REPO} ${FILENAME}.tar.gz
      shell: bash
